### ISSUE TITLE
Mysterious Travis build failure

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1332]
In 
https://github.com/bedita/bedita/commit/94a70ea34e1d2d2bd24d7bef0e21e72cc193c07c
after #1323 this failing build was removed:

```yaml
  - stage: complete
    php: 7.0
    env: "DB=pgsql DB_VERSION=9.6 db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
```

Tests are OK, but then this nice message appears
```
/home/travis/.travis/job_stages: line 57:  6632 Segmentation fault      (core dumped) vendor/bin/phpunit
```
